[package]
name = "dank-image"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

dither = "=1.3.6"
image = "0.23"

reqwest = "0.11.12"